dirs:
  checks: /home/niar/checks

hostname: vps-01

services:
  telegram:
    url: telegram://${TELEGRAM_TOKEN}@telegram
    params:
      chats: ${TELEGRAM_CHAT_ID}

alerts:
  - name: disk_check
    check: file://disk_usage
    trigger:
      interval: 30s
    timeout: 10s
    cooldown: 5m
    template: "{{check.status | upper}} {{globals.hostname}}: Disk at {{check.usage_percent}}%"
    notify:
      - telegram
