options:
  healthchecks_dir: /home/niar/healthchecks

globals:
  hostname: vps-01

services:
  telegram:
    url: telegram://${TELEGRAM_TOKEN}@telegram
    params:
      chats: ${TELEGRAM_CHAT_ID}

alerts:
  - name: disk_check
    healthcheck: file://disk_usage
    trigger:
      interval: 30s
    timeout: 10s
    cooldown: 5m
    args:
      threshold_warn: 0.80
      threshold_crit: 0.90
    template: |-
      [{{healthcheck.status | upper}}] {{globals.hostname}} {{healthcheck.used}}:
      Disk at {{healthcheck.usage_percent}}%
    notify:
      - telegram
